Repository deveassy/react-wedding-card, pull requests merged in 2021-06, with the labels that each got.

#9 계좌번호 modal 작업
  package.json
  src/components/Header/styles.ts
  src/components/Modal/index.tsx
  src/components/Modal/styles.ts
  src/containers/BridePage/index.tsx
  src/containers/BridePage/styles.ts
  src/containers/GroomPage/index.tsx
  src/containers/GroomPage/styles.ts
  src/containers/MainPage/index.tsx
  tsconfig.json
  yarn.lock
Labels: feature

#10 Feat/swiper
  package.json
  src/containers/BridePage/index.tsx
  src/containers/MainPage/index.tsx
  src/containers/MainPage/styles.ts
  yarn.lock
Labels: feature

#17 Feat/likeit
  public/img/emptyHeart.png
  src/App.tsx
  src/components/Header/styles.ts
  src/containers/MainPage/index.tsx
  src/containers/MainPage/styles.ts
  src/globals/fonts/KaushanScript-Regular.ttf
  src/globals/fonts/Rancho-Regular.ttf
  src/globals/styles.js
  src/globals/styles.ts
Labels: feature

#19 Feat/comment
  src/components/Comment/index.tsx
  src/components/Comment/styles.ts
  src/components/index.ts
  src/containers/MainPage/index.tsx
  src/containers/MainPage/styles.ts
Labels: feature

#23 Feat/redux
  package.json
  src/App.tsx
  src/components/Comment/index.tsx
  src/components/Like/index.tsx
  src/components/Like/styles.ts
  src/components/Swiper/index.tsx
  src/components/Swiper/styles.ts
  src/components/index.ts
  src/containers/MainPage/index.tsx
  src/containers/MainPage/styles.ts
  src/containers/MapPage/index.tsx
  src/mocks/post.json
  src/modules/index.ts
  src/modules/post.ts
  src/types/index.d.ts
  yarn.lock
Labels: feature

#25 comment UI 폴더 기능 추가
  src/components/Comment/index.tsx
  src/components/Comment/styles.ts
  src/containers/MainPage/styles.ts
Labels: enhance

#26 fetch작업 완료
  src/App.tsx
  src/components/Comment/index.tsx
  src/components/Comment/styles.ts
  src/components/Like/index.tsx
  src/types/index.d.ts
Labels: feature

#27 Enh/update styling
  public/img/logo.png
  src/components/Comment/styles.ts
  src/components/Header/index.tsx
  src/components/Header/styles.ts
  src/components/Modal/styles.ts
  src/components/Swiper/index.tsx
  src/components/Swiper/styles.ts
  src/containers/BridePage/index.tsx
  src/containers/BridePage/styles.ts
  src/containers/GroomPage/index.tsx
  src/containers/GroomPage/styles.ts
  src/containers/MainPage/index.tsx
  src/containers/MainPage/styles.ts
  src/containers/MapPage/index.tsx
  src/containers/MapPage/styles.ts
  src/globals/fonts/CaveatBrush-Regular.ttf
  src/globals/fonts/EastSeaDokdo-Regular.ttf
  src/globals/fonts/KaushanScript-Regular.ttf
  src/globals/fonts/Lato-Regular.ttf
  src/globals/fonts/Rancho-Regular.ttf
  src/globals/styles.js
Labels: enhance

#28 Bugfix/minor fix 01
  src/components/Like/index.tsx
  src/containers/MapPage/index.tsx
  src/modules/post.ts
Labels: bugfix, enhance
